### ISSUE TITLE
Remove warning against null root

### ISSUE THREAD

**Issue by sudhirj** [TejasQ/react-hook-intersection-observer#2]
The hooks warns against using a null root [here](https://github.com/TejasQ/react-hook-intersection-observer/blob/master/src/index.js#L8), but that is actually the perfectly valid default case, maybe even the 99% case. 

The [MDN article quoted](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Intersection_observer_concepts_and_usage
) as reasoning itself is clear about this: 
> ...this is called the root element or root. Typically, you'll want to watch for intersection changes with regard to the document's viewport (which is done by specifying null as the root element ).

Would suggest removing the warning because it pollutes the console for what is really a valid and the most common use case.

**Comment by sudhirj** [comment]
It might make sense to warn the user when a root ref *is* actually passed in, but that ref is null, as in `if (root && !root.current) { console.warn }`

**Comment by TejasQ** [comment]
Great report! Would you like to open a PR and work together towards a solution? 🎉

**Comment by sudhirj** [comment]
Let me finish implementing the intersection observer and then report back, might make sense to do a different kind of solution altogether.
